In [2]:
# ============================================================================
# GEMMA-3-1B QLORA FINE-TUNING (100 SAMPLES - FIXED)
# ============================================================================

!pip install -q -U accelerate peft bitsandbytes transformers trl datasets

import os, gc, time, torch, shutil, sys
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments, TrainerCallback
)
from peft import LoraConfig
from trl import SFTTrainer
from huggingface_hub import login
from google.colab import userdata, drive

gc.collect()
torch.cuda.empty_cache()

drive.mount('/content/drive')
login(token=userdata.get('HF_TOKEN'))

MODEL_NAME        = "google/gemma-3-1b-it"
DATASET_NAME      = "b-mc2/sql-create-context"
OUTPUT_DIR        = "./gemma-sql-finetuned"
NEW_MODEL_NAME    = "gemma-1b-sql-generator"
LOCAL_SAVE_PATH   = f"/content/{NEW_MODEL_NAME}"        # Colab local folder
DRIVE_BACKUP_PATH = f"/content/drive/MyDrive/{NEW_MODEL_NAME}"  # Google Drive folder

# ============================================================================
# 100 SAMPLES
# ============================================================================
dataset = load_dataset(DATASET_NAME, split="train")
dataset = dataset.select(range(100))

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

def format_sql_prompt(example):
    text = f"""<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: {example['context']}
Question: {example['question']}<end_of_turn>
<start_of_turn>model
{example['answer']}<end_of_turn><eos>"""
    return {"text": text}

dataset = dataset.map(format_sql_prompt, remove_columns=dataset.column_names)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, quantization_config=bnb_config,
    device_map="auto", trust_remote_code=True
)
model.config.use_cache = False

peft_config = LoraConfig(
    r=8, lora_alpha=16, lora_dropout=0.05, bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

# FIX: fp16=False, bf16=False - required for bitsandbytes 4-bit
training_arguments = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    logging_steps=1,
    logging_strategy="steps",
    learning_rate=2e-4,
    fp16=False,                     # MUST be False with bitsandbytes 4-bit
    bf16=False,                     # MUST be False with bitsandbytes 4-bit
    max_grad_norm=0.3,
    warmup_steps=5,
    lr_scheduler_type="cosine",
    report_to="none",
    save_strategy="epoch",
)

class ProgressCallback(TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        if state.max_steps > 0:
            pct = state.global_step / state.max_steps * 100
            filled = int(20 * state.global_step // state.max_steps)
            bar = '█' * filled + '░' * (20 - filled)
            print(f"\rStep {state.global_step}/{state.max_steps} |{bar}| {pct:.0f}%", end="")
            sys.stdout.flush()
    def on_train_end(self, args, state, control, **kwargs):
        print("\n✅ Done!")

trainer = SFTTrainer(
    model=model, train_dataset=dataset,
    peft_config=peft_config, processing_class=tokenizer,
    args=training_arguments,
)
trainer.max_seq_length = 256
trainer.packing = False
trainer.add_callback(ProgressCallback())

print("=" * 60)
print("TRAINING ON 100 SAMPLES (~10 seconds)")
print("=" * 60)

start_time = time.time()
trainer.train()
print(f"Time: {(time.time() - start_time):.1f}s")

# ============================================================================
# SAVE TO LOCAL FOLDER
# ============================================================================
os.makedirs(LOCAL_SAVE_PATH, exist_ok=True)
trainer.model.save_pretrained(LOCAL_SAVE_PATH)
tokenizer.save_pretrained(LOCAL_SAVE_PATH)
print(f"✅ Saved locally: {LOCAL_SAVE_PATH}")

# ============================================================================
# SAVE TO GOOGLE DRIVE
# ============================================================================
os.makedirs(DRIVE_BACKUP_PATH, exist_ok=True)
shutil.copytree(LOCAL_SAVE_PATH, DRIVE_BACKUP_PATH, dirs_exist_ok=True)
print(f"✅ Saved to Drive: {DRIVE_BACKUP_PATH}")

# Show files
print("\n📁 Files saved:")
for file in os.listdir(LOCAL_SAVE_PATH):
    size_kb = os.path.getsize(os.path.join(LOCAL_SAVE_PATH, file)) / 1024
    print(f"   📄 {file} ({size_kb:.1f} KB)")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 1, 'pad_token_id': 1}.

============================================================
TRAINING ON 100 SAMPLES (~10 seconds)
============================================================

Step 7/7 |████████████████████| 100%
✅ Done!
Time: 19.4s
✅ Saved locally: /content/gemma-1b-sql-generator
✅ Saved to Drive: /content/drive/MyDrive/gemma-1b-sql-generator

📁 Files saved:
   📄 tokenizer.json (32602.1 KB)
   📄 adapter_model.safetensors (1469.3 KB)
   📄 tokenizer_config.json (0.7 KB)
   📄 chat_template.jinja (1.5 KB)
   📄 README.md (5.1 KB)
   📄 adapter_config.json (1.0 KB)

In [4]:
!pip install -q torchao==0.9.0 peft==0.13.2

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 76.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.7/320.7 kB 32.6 MB/s eta 0:00:00

In [5]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

# Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-3-1b-it",
    device_map="auto",
    torch_dtype=torch.float16
)

# Load your LoRA adapters
model = PeftModel.from_pretrained(base_model, "/content/gemma-1b-sql-generator")
tokenizer = AutoTokenizer.from_pretrained("/content/gemma-1b-sql-generator")

# Test query
prompt = """<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT);
Question: How many employees are there?<end_of_turn>
<start_of_turn>model
"""

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=100)
sql = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(sql.split("<start_of_turn>model\n")[-1])

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

ImportError: Found an incompatible version of torchao. Found version 0.9.0, but only versions above 0.16.0 are supported

In [7]:
# ============================================================================
# FIX: Install compatible versions first
# ============================================================================
!pip install -q torchao==0.16.0 peft==0.14.0

# ============================================================================
# TEST YOUR TRAINED SQL MODEL
# ============================================================================
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

# Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-3-1b-it",
    device_map="auto",
    dtype=torch.float16            # Use 'dtype' not 'torch_dtype'
)

# Load your LoRA adapters
model = PeftModel.from_pretrained(base_model, "/content/gemma-1b-sql-generator")
tokenizer = AutoTokenizer.from_pretrained("/content/gemma-1b-sql-generator")

# Test query
prompt = """<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT);
Question: How many employees are there?<end_of_turn>
<start_of_turn>model
"""

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=100)
sql = tokenizer.decode(outputs[0], skip_special_tokens=True)

# Extract only the SQL part
result = sql.split("<start_of_turn>model\n")[-1].strip()
print(f"Generated SQL: {result}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 59.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 36.8 MB/s eta 0:00:00

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Generated SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT);
Question: How many employees are there?
model
```sql
SELECT COUNT(*) FROM employees;
```

In [8]:
# ============================================================================
# GEMMA-3-1B QLORA FINE-TUNING (1000 SAMPLES)
# ============================================================================

!pip install -q -U accelerate peft bitsandbytes transformers trl datasets

import os, gc, time, torch, shutil, sys
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments, TrainerCallback
)
from peft import LoraConfig
from trl import SFTTrainer
from huggingface_hub import login
from google.colab import userdata, drive

gc.collect()
torch.cuda.empty_cache()

drive.mount('/content/drive')
login(token=userdata.get('HF_TOKEN'))

MODEL_NAME        = "google/gemma-3-1b-it"
DATASET_NAME      = "b-mc2/sql-create-context"
OUTPUT_DIR        = "./gemma-sql-finetuned-1000"
NEW_MODEL_NAME    = "gemma-1b-sql-generator-1000"
LOCAL_SAVE_PATH   = f"/content/{NEW_MODEL_NAME}"
DRIVE_BACKUP_PATH = f"/content/drive/MyDrive/{NEW_MODEL_NAME}"

# ============================================================================
# 1000 SAMPLES
# ============================================================================
dataset = load_dataset(DATASET_NAME, split="train")
dataset = dataset.select(range(1000))  # Changed to 1000

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

def format_sql_prompt(example):
    text = f"""<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: {example['context']}
Question: {example['question']}<end_of_turn>
<start_of_turn>model
{example['answer']}<end_of_turn><eos>"""
    return {"text": text}

dataset = dataset.map(format_sql_prompt, remove_columns=dataset.column_names)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, quantization_config=bnb_config,
    device_map="auto", trust_remote_code=True
)
model.config.use_cache = False

peft_config = LoraConfig(
    r=8, lora_alpha=16, lora_dropout=0.05, bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

training_arguments = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    logging_steps=1,
    logging_strategy="steps",
    learning_rate=2e-4,
    fp16=False,
    bf16=False,
    max_grad_norm=0.3,
    warmup_steps=5,
    lr_scheduler_type="cosine",
    report_to="none",
    save_strategy="epoch",
)

class ProgressCallback(TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        if state.max_steps > 0:
            pct = state.global_step / state.max_steps * 100
            filled = int(20 * state.global_step // state.max_steps)
            bar = '█' * filled + '░' * (20 - filled)
            print(f"\rStep {state.global_step}/{state.max_steps} |{bar}| {pct:.0f}%", end="")
            sys.stdout.flush()
    def on_train_end(self, args, state, control, **kwargs):
        print("\n✅ Done!")

trainer = SFTTrainer(
    model=model, train_dataset=dataset,
    peft_config=peft_config, processing_class=tokenizer,
    args=training_arguments,
)
trainer.max_seq_length = 256
trainer.packing = False
trainer.add_callback(ProgressCallback())

print("=" * 60)
print("TRAINING ON 1000 SAMPLES (~1 minute)")
print("=" * 60)

start_time = time.time()
trainer.train()
print(f"Time: {(time.time() - start_time):.1f}s")

# ============================================================================
# SAVE
# ============================================================================
os.makedirs(LOCAL_SAVE_PATH, exist_ok=True)
trainer.model.save_pretrained(LOCAL_SAVE_PATH)
tokenizer.save_pretrained(LOCAL_SAVE_PATH)
print(f"✅ Saved locally: {LOCAL_SAVE_PATH}")

os.makedirs(DRIVE_BACKUP_PATH, exist_ok=True)
shutil.copytree(LOCAL_SAVE_PATH, DRIVE_BACKUP_PATH, dirs_exist_ok=True)
print(f"✅ Saved to Drive: {DRIVE_BACKUP_PATH}")

print("\n📁 Files saved:")
for file in os.listdir(LOCAL_SAVE_PATH):
    size_kb = os.path.getsize(os.path.join(LOCAL_SAVE_PATH, file)) / 1024
    print(f"   📄 {file} ({size_kb:.1f} KB)")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 680.7/680.7 kB 15.0 MB/s eta 0:00:00
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Adding EOS to train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 1, 'pad_token_id': 1}.

============================================================
TRAINING ON 1000 SAMPLES (~1 minute)
============================================================

Step 63/63 |████████████████████| 100%
✅ Done!
Time: 183.3s
✅ Saved locally: /content/gemma-1b-sql-generator-1000
✅ Saved to Drive: /content/drive/MyDrive/gemma-1b-sql-generator-1000

📁 Files saved:
   📄 tokenizer.json (32602.1 KB)
   📄 adapter_model.safetensors (1469.3 KB)
   📄 tokenizer_config.json (0.7 KB)
   📄 chat_template.jinja (1.5 KB)
   📄 README.md (5.1 KB)
   📄 adapter_config.json (1.0 KB)

In [9]:
# ============================================================================
# COMPARE: BASE MODEL vs FINE-TUNED MODEL
# ============================================================================

!pip install -q transformers torch

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch
import time

# ============================================================================
# TEST QUERIES (Easy / Medium / Hard)
# ============================================================================
test_cases = [
    {
        "name": "Easy - Simple SELECT",
        "schema": "CREATE TABLE employees (id INT, name TEXT, department TEXT);",
        "question": "How many employees are there?"
    },
    {
        "name": "Medium - WHERE clause",
        "schema": "CREATE TABLE employees (id INT, name TEXT, department TEXT, salary REAL);",
        "question": "List all employees in the sales department"
    },
    {
        "name": "Hard - JOIN",
        "schema": "CREATE TABLE customers (id INT, name TEXT); CREATE TABLE orders (id INT, customer_id INT, amount REAL);",
        "question": "List customer names with their order amounts"
    }
]

# ============================================================================
# LOAD BASE MODEL (Non Fine-Tuned)
# ============================================================================
print("=" * 60)
print("LOADING BASE GEMMA MODEL (Non Fine-Tuned)")
print("=" * 60)

base_model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-3-1b-it",
    device_map="auto",
    dtype=torch.float16
)
base_tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-1b-it")

# ============================================================================
# LOAD FINE-TUNED MODEL
# ============================================================================
print("\n" + "=" * 60)
print("LOADING FINE-TUNED MODEL (1000 samples)")
print("=" * 60)

ft_model = AutoModelForCausalLM.from_pretrained(
    "/content/gemma-1b-sql-generator-1000",
    device_map="auto",
    dtype=torch.float16
)
ft_tokenizer = AutoTokenizer.from_pretrained("/content/gemma-1b-sql-generator-1000")

# ============================================================================
# FUNCTION TO GENERATE SQL
# ============================================================================
def generate_sql(model, tokenizer, schema, question, model_name):
    prompt = f"""<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: {schema}
Question: {question}<end_of_turn>
<start_of_turn>model
"""
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    start = time.time()
    outputs = model.generate(**inputs, max_new_tokens=150, temperature=0.1)
    elapsed = time.time() - start

    sql = tokenizer.decode(outputs[0], skip_special_tokens=True)
    result = sql.split("<start_of_turn>model\n")[-1].split("<end_of_turn>")[0].strip()

    return result, elapsed

# ============================================================================
# RUN COMPARISON
# ============================================================================
print("\n" + "=" * 60)
print("COMPARISON RESULTS")
print("=" * 60)

for test in test_cases:
    print(f"\n{'─' * 60}")
    print(f"📝 {test['name']}")
    print(f"   Schema:   {test['schema'][:60]}...")
    print(f"   Question: {test['question']}")
    print(f"{'─' * 60}")

    # Base model
    base_sql, base_time = generate_sql(base_model, base_tokenizer, test['schema'], test['question'], "Base")
    print(f"\n🔴 BASE MODEL (Non Fine-Tuned) - {base_time:.2f}s")
    print(f"   SQL: {base_sql}")

    # Fine-tuned model
    ft_sql, ft_time = generate_sql(ft_model, ft_tokenizer, test['schema'], test['question'], "Fine-Tuned")
    print(f"\n🟢 FINE-TUNED MODEL (1000 samples) - {ft_time:.2f}s")
    print(f"   SQL: {ft_sql}")

print("\n" + "=" * 60)
print("COMPARISON COMPLETE!")
print("=" * 60)

============================================================
LOADING BASE GEMMA MODEL (Non Fine-Tuned)
============================================================

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

============================================================
LOADING FINE-TUNED MODEL (1000 samples)
============================================================

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

============================================================
COMPARISON RESULTS
============================================================

────────────────────────────────────────────────────────────
📝 Easy - Simple SELECT
   Schema:   CREATE TABLE employees (id INT, name TEXT, department TEXT);...
   Question: How many employees are there?
────────────────────────────────────────────────────────────

🔴 BASE MODEL (Non Fine-Tuned) - 0.99s
   SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT);
Question: How many employees are there?
model
```sql
SELECT COUNT(*) FROM employees;
```

🟢 FINE-TUNED MODEL (1000 samples) - 0.59s
   SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT);
Question: How many employees are there?
model
SELECT COUNT(*) FROM employees

────────────────────────────────────────────────────────────
📝 Medium - WHERE clause
   Schema:   CREATE TABLE employees (id INT, name TEXT, department TEXT, ...
   Question: List all employees in the sales department
────────────────────────────────────────────────────────────

🔴 BASE MODEL (Non Fine-Tuned) - 1.42s
   SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT, salary REAL);
Question: List all employees in the sales department
model
```sql
SELECT *
FROM employees
WHERE department = 'Sales';
```

🟢 FINE-TUNED MODEL (1000 samples) - 1.02s
   SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE employees (id INT, name TEXT, department TEXT, salary REAL);
Question: List all employees in the sales department
model
SELECT * FROM employees WHERE department = 'Sales'

────────────────────────────────────────────────────────────
📝 Hard - JOIN
   Schema:   CREATE TABLE customers (id INT, name TEXT); CREATE TABLE ord...
   Question: List customer names with their order amounts
────────────────────────────────────────────────────────────

🔴 BASE MODEL (Non Fine-Tuned) - 1.91s
   SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE customers (id INT, name TEXT); CREATE TABLE orders (id INT, customer_id INT, amount REAL);
Question: List customer names with their order amounts
model
```sql
SELECT c.name, o.amount
FROM customers c
JOIN orders o ON c.id = o.customer_id;
```

🟢 FINE-TUNED MODEL (1000 samples) - 2.10s
   SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE customers (id INT, name TEXT); CREATE TABLE orders (id INT, customer_id INT, amount REAL);
Question: List customer names with their order amounts
model
SELECT c.name FROM customers AS c JOIN orders AS o ON c.id = o.customer_id WHERE o.amount > 1000

============================================================
COMPARISON COMPLETE!
============================================================

In [10]:
# ============================================================================
# CLEAR CPU & GPU MEMORY
# ============================================================================

import gc
import torch

# Clear GPU cache
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()
torch.cuda.synchronize()

# Run garbage collector multiple times
gc.collect()
gc.collect()
gc.collect()

# Print memory status
print("=" * 40)
print("MEMORY STATUS")
print("=" * 40)
print(f"GPU Allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
print(f"GPU Cached:    {torch.cuda.memory_reserved() / 1024**3:.2f} GB")
print(f"GPU Free:      {torch.cuda.mem_get_info()[0] / 1024**3:.2f} GB")
print(f"GPU Total:     {torch.cuda.mem_get_info()[1] / 1024**3:.2f} GB")
print("=" * 40)
print("✅ Memory cleared! Ready for training.")

========================================
MEMORY STATUS
========================================
GPU Allocated: 6.57 GB
GPU Cached:    7.54 GB
GPU Free:      6.88 GB
GPU Total:     14.56 GB
========================================
✅ Memory cleared! Ready for training.

In [11]:
# ============================================================================
# FINAL: GEMMA-3-1B QLORA FINE-TUNING (2000 SAMPLES, 2 EPOCHS, SHUFFLED)
# ============================================================================

!pip install -q -U accelerate peft bitsandbytes transformers trl datasets

import os, gc, time, torch, shutil, sys
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments, TrainerCallback
)
from peft import LoraConfig
from trl import SFTTrainer
from huggingface_hub import login
from google.colab import userdata, drive

gc.collect()
torch.cuda.empty_cache()

drive.mount('/content/drive')
login(token=userdata.get('HF_TOKEN'))

MODEL_NAME        = "google/gemma-3-1b-it"
DATASET_NAME      = "b-mc2/sql-create-context"
OUTPUT_DIR        = "./gemma-sql-finetuned-final"
NEW_MODEL_NAME    = "gemma-1b-sql-final-2000-suffled"
LOCAL_SAVE_PATH   = f"/content/{NEW_MODEL_NAME}"
DRIVE_BACKUP_PATH = f"/content/drive/MyDrive/{NEW_MODEL_NAME}"

# ============================================================================
# 2000 SAMPLES - SHUFFLED FOR DIVERSITY
# ============================================================================
dataset = load_dataset(DATASET_NAME, split="train")
dataset = dataset.shuffle(seed=42).select(range(2000))

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

def format_sql_prompt(example):
    text = f"""<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: {example['context']}
Question: {example['question']}<end_of_turn>
<start_of_turn>model
{example['answer']}<end_of_turn><eos>"""
    return {"text": text}

dataset = dataset.map(format_sql_prompt, remove_columns=dataset.column_names)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, quantization_config=bnb_config,
    device_map="auto", trust_remote_code=True
)
model.config.use_cache = False

peft_config = LoraConfig(
    r=8, lora_alpha=16, lora_dropout=0.05, bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

training_arguments = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=2,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    logging_steps=1,
    logging_strategy="steps",
    learning_rate=2e-4,
    fp16=False, bf16=False,
    max_grad_norm=0.3,
    warmup_steps=5,
    lr_scheduler_type="cosine",
    report_to="none",
    save_strategy="epoch",
)

class ProgressCallback(TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        if state.max_steps > 0:
            pct = state.global_step / state.max_steps * 100
            filled = int(20 * state.global_step // state.max_steps)
            bar = '█' * filled + '░' * (20 - filled)
            print(f"\rStep {state.global_step}/{state.max_steps} |{bar}| {pct:.0f}%", end="")
            sys.stdout.flush()
    def on_train_end(self, args, state, control, **kwargs):
        print("\n✅ Training Complete!")

trainer = SFTTrainer(
    model=model, train_dataset=dataset,
    peft_config=peft_config, processing_class=tokenizer,
    args=training_arguments,
)
trainer.max_seq_length = 256
trainer.packing = False
trainer.add_callback(ProgressCallback())

print("=" * 60)
print("FINAL TRAINING: 2000 Samples | 2 Epochs | Shuffled")
print("=" * 60)

trainer.train()

# ============================================================================
# SAVE
# ============================================================================
os.makedirs(LOCAL_SAVE_PATH, exist_ok=True)
trainer.model.save_pretrained(LOCAL_SAVE_PATH)
tokenizer.save_pretrained(LOCAL_SAVE_PATH)
print(f"✅ Saved locally: {LOCAL_SAVE_PATH}")

os.makedirs(DRIVE_BACKUP_PATH, exist_ok=True)
shutil.copytree(LOCAL_SAVE_PATH, DRIVE_BACKUP_PATH, dirs_exist_ok=True)
print(f"✅ Saved to Drive: {DRIVE_BACKUP_PATH}")

# ============================================================================
# QUICK TEST
# ============================================================================
print("\n" + "=" * 60)
print("QUICK TEST - GENERATING SQL")
print("=" * 60)

test_prompt = """<bos><start_of_turn>system
You are an expert SQL assistant. Write only the SQL query, no explanation.<end_of_turn>
<start_of_turn>user
Schema: CREATE TABLE customers (id INT, name TEXT); CREATE TABLE orders (id INT, customer_id INT, amount REAL);
Question: List customer names with their order amounts<end_of_turn>
<start_of_turn>model
"""

inputs = tokenizer(test_prompt, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=100, temperature=0.1)
sql = tokenizer.decode(outputs[0], skip_special_tokens=True)
result = sql.split("<start_of_turn>model\n")[-1].split("<end_of_turn>")[0].strip()

print(f"Schema: CREATE TABLE customers..., CREATE TABLE orders...")
print(f"Question: List customer names with their order amounts")
print(f"Generated SQL: {result}")
print("=" * 60)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Adding EOS to train dataset:   0%|          | 0/2000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/2000 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 1, 'pad_token_id': 1}.

============================================================
FINAL TRAINING: 2000 Samples | 2 Epochs | Shuffled
============================================================

Step 250/250 |████████████████████| 100%
✅ Training Complete!
✅ Saved locally: /content/gemma-1b-sql-final-2000-suffled
✅ Saved to Drive: /content/drive/MyDrive/gemma-1b-sql-final-2000-suffled

============================================================
QUICK TEST - GENERATING SQL
============================================================
Schema: CREATE TABLE customers..., CREATE TABLE orders...
Question: List customer names with their order amounts
Generated SQL: system
You are an expert SQL assistant. Write only the SQL query, no explanation.
user
Schema: CREATE TABLE customers (id INT, name TEXT); CREATE TABLE orders (id INT, customer_id INT, amount REAL);
Question: List customer names with their order amounts
model
SELECT c.name FROM customers AS c JOIN orders AS o ON c.id = o.customer_id WHERE o.amount = 0.01
============================================================

In [12]:
from google.colab import files
import shutil

shutil.make_archive("gemma-1b-sql-final-2000-suffled", 'zip',
                    "/content/gemma-1b-sql-final-2000-suffled")

files.download("gemma-1b-sql-final-2000-suffled.zip")

In [14]:
from huggingface_hub import HfApi

api = HfApi()

# Create the repo first
api.create_repo(
    repo_id="adityaXXXXXX/gemma-1b-sql-final-2000-suffled",
    repo_type="model",
    exist_ok=True
)

# Upload the folder
api.upload_folder(
    folder_path="/content/gemma-1b-sql-final-2000-suffled",  # local path in Colab
    repo_id="adityaXXXXXX/gemma-1b-sql-final-2000-suffled",
    repo_type="model"
)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   1%|          | 11.6kB / 1.50MB

  ...00-suffled/tokenizer.json: 100%|##########| 33.4MB / 33.4MB

CommitInfo(commit_url='https://huggingface.co/adityaXXXXXX/gemma-1b-sql-final-2000-suffled/commit/7afee0397ac0cb0246e59f51db1b844e6ea37e12', commit_message='Upload folder using huggingface_hub', commit_description='', oid='7afee0397ac0cb0246e59f51db1b844e6ea37e12', pr_url=None, repo_url=RepoUrl('https://huggingface.co/adityaXXXXXX/gemma-1b-sql-final-2000-suffled', endpoint='https://huggingface.co', repo_type='model', repo_id='adityaXXXXXX/gemma-1b-sql-final-2000-suffled'), pr_revision=None, pr_num=None)

In [15]:
!pip install transformers peft accelerate bitsandbytes -q

In [19]:
from huggingface_hub import login
login()  # apna HF token paste kar

In [22]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

MODEL_ID = "google/gemma-3-1b-it"  # sahi naam

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto"
)

model = PeftModel.from_pretrained(model, "adityaXXXXXX/gemma-1b-sql-final-2000-suffled")
model.eval()
print("Model loaded!")

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Model loaded!

In [23]:
question = "Get all employees with salary greater than 50000"
prompt = f"### Question: {question}\n### SQL:"

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(**inputs, max_new_tokens=128, do_sample=False)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

### Question: Get all employees with salary greater than 50000
### SQL: SELECT employee_name FROM employees WHERE salary > 50000
### Answer: Employees with salary greater than 50000
### Question: Get all employees with salary greater than 50000
### SQL: SELECT employee_name FROM employees WHERE salary > 50000
### Answer: Employees with salary greater than 50000
### Question: Get all employees with salary greater than 50000
### SQL: SELECT employee_name FROM employees WHERE salary > 50000
### Answer: Employees with salary greater than 5

In [24]:
def generate_sql(question: str) -> str:
    prompt = f"### Question: {question}\n### SQL:"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=128,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.3  # loop rokta hai
        )

    # sirf SQL part nikalo
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    sql = decoded.split("### SQL:")[-1].split("### Answer:")[0].strip()
    return sql

# test
print(generate_sql("Get all employees with salary greater than 50000"))

SELECT employee_name FROM staff WHERE salary > 50000

In [26]:
pip install modal

Collecting modal
  Downloading modal-1.4.2-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from modal) (3.13.5)
Collecting cbor2 (from modal)
  Downloading cbor2-6.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from modal) (2026.4.22)
Requirement already satisfied: click~=8.1 in /usr/local/lib/python3.12/dist-packages (from modal) (8.3.3)
Requirement already satisfied: grpclib<0.4.10,>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from modal) (0.4.9)
Requirement already satisfied: protobuf!=4.24.0,<7.0,>=3.19 in /usr/local/lib/python3.12/dist-packages (from modal) (5.29.6)
Requirement already satisfied: rich>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from modal) (13.9.4)
Collecting synchronicity~=0.12.1 (from modal)
  Downloading synchronicity-0.12.2-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: toml in /usr/local/lib/python3.12/dist-packages (from modal) (0.10.2)
Requirement already satisfied: typer>=0.9 in /usr/local/lib/python3.12/dist-packages (from modal) (0.24.2)
Collecting types-certifi (from modal)
  Downloading types_certifi-2021.10.8.3-py3-none-any.whl.metadata (1.4 kB)
Collecting types-toml (from modal)
  Downloading types_toml-0.10.8.20260408-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from modal) (1.1.1)
Requirement already satisfied: typing_extensions~=4.6 in /usr/local/lib/python3.12/dist-packages (from modal) (4.15.0)
Requirement already satisfied: h2<5,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from grpclib<0.4.10,>=0.4.7->modal) (4.3.0)
Requirement already satisfied: multidict in /usr/local/lib/python3.12/dist-packages (from grpclib<0.4.10,>=0.4.7->modal) (6.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.0.0->modal) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.0.0->modal) (2.20.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9->modal) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9->modal) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->modal) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->modal) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->modal) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->modal) (1.8.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->modal) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->modal) (1.23.0)
Requirement already satisfied: anyio>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from watchfiles->modal) (4.13.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=3.0.0->watchfiles->modal) (3.13)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3.1.0->grpclib<0.4.10,>=0.4.7->modal) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3.1.0->grpclib<0.4.10,>=0.4.7->modal) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->modal) (0.1.2)
Downloading modal-1.4.2-py3-none-any.whl (802 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.8/802.8 kB 18.9 MB/s eta 0:00:00
Downloading synchronicity-0.12.2-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 4.8 MB/s eta 0:00:00
Downloading cbor2-6.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (456 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 456.5/456.5 kB 41.0 MB/s eta 0:00:00
Downloading types_certifi-2021.10.8.3-py3-none-any.whl (2.1 kB)
Downloading types_toml-0.10.8.20260408-py3-none-any.whl (9.7 kB)
Installing collected packages: types-certifi, types-toml, synchronicity, cbor2, modal
Successfully installed cbor2-6.0.1 modal-1.4.2 synchronicity-0.12.2 types-certifi-2021.10.8.3 types-toml-0.10.8.20260408

In [28]:
modal setup

SyntaxError: invalid syntax (2897894272.py, line 1)

In [ ]:
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